sqlite3 QRN.db "
CREATE TABLE QRN_QURAN_OTHMAN(
 "S" INTEGER,
 "A" INTEGER,
 "VERSE" TEXT
);"

sqlite3 QRN.db "
CREATE TABLE QRN_SURAH_NAME(
 "S" INTEGER,
 "ARAB_NAME" TEXT,
 "ARAB_NAME_PHONETIC" TEXT,
 "TRANSLATION" TEXT,
 "NB_VERSES" INTEGER,
 "PLACE" TEXT,
 "TRANSMISSION_ORDER" INTEGER
);"

sqlite3 QRN.db "
CREATE TABLE QRN_QWLC(
  "S" INTEGER,
  "A" INTEGER,
  "VAL" INTEGER,
  "NUM" INTEGER,
  "POS" INTEGER,
  "C" INTEGER,
  "V" INTEGER,
  "D" INTEGER,
  "FATHA_TANWIN" INTEGER,
  "MADDA_EN_CHEF" INTEGER,
  "ALIF_SOUSCRIT" INTEGER,
  "CHADDA" INTEGER,
  "SUKKUN" INTEGER,
  "DAMMA" INTEGER,
  "DAMMA_TANWIN" INTEGER,
  "FATHA" INTEGER,
  "KASRA" INTEGER,
  "KASRA_TANWIN" INTEGER,
  "ALIF" INTEGER,
  "ALIF_WASLA" INTEGER,
  "ALIF_HAMZA" INTEGER,
  "ALIF_HAMZA_SOUSCRIT" INTEGER,
  "ALIF_HAMZA_EN_CHEF" INTEGER,
  "BA" INTEGER,
  "JIM" INTEGER,
  "DAL" INTEGER,
  "HA" INTEGER,
  "WAW" INTEGER,
  "WAW_HAMZA" INTEGER,
  "PETIT_WAW" INTEGER,
  "ZAY" INTEGER,
  "HHA" INTEGER,
  "TAA" INTEGER,
  "YA" INTEGER,
  "PETIT_YA" INTEGER,
  "YA_HAMZA" INTEGER,
  "KAF" INTEGER,
  "LAM" INTEGER,
  "MIM" INTEGER,
  "PETIT_MIM" INTEGER,
  "PETIT_MIM_SOUSCRIT" INTEGER,
  "NUN" INTEGER,
  "PETIT_NUN_HAUT" INTEGER,
  "SIN" INTEGER,
  "PETIT_SIN_BAT" INTEGER,
  "PETIT_SIN_HAUT" INTEGER,
  "AYN" INTEGER,
  "FA" INTEGER,
  "SAD" INTEGER,
  "QAF" INTEGER,
  "RA" INTEGER,
  "SHIN" INTEGER,
  "TA" INTEGER,
  "THA" INTEGER,
  "KHA" INTEGER,
  "DHAL" INTEGER,
  "DAD" INTEGER,
  "ZA" INTEGER,
  "RHAYN" INTEGER,
  "TA_MARBUTA" INTEGER,
  "ALIF_MAQSURA" INTEGER,
  "HAMZA" INTEGER,
  "HAMZA_AU_DESSUS" INTEGER,
  "ZERO" INTEGER,
  "ZERO_RECTANGLE" INTEGER,
  "PETIT_STOP" INTEGER,
  "PETIT_STOP_HAUT" INTEGER,
  "PETIT_STOP_HAUT_REMPLI" INTEGER,
  "MOT" TEXT
);"
sqlite3 QRN.db "CREATE TABLE QRN_ABJAD_VERSES(
  "S" INTEGER,
  "A" INTEGER,
  "ABJAD" INTEGER,
  "NB_WORDS" INTEGER,
  "NB_CHAR" INTEGER
);"

sqlite3 QRN.db "CREATE TABLE QRN_ABJAD_WORDS(
  "S" INTEGER,
  "A" INTEGER,
  "POS" INTEGER,
  "NB_CHAR" INTEGER,
  "ABJAD" INTEGER,
  "ABJAD_DEBUG" TEXT,
  "WORD" TEXT
);"

sqlite3 QRN.db "CREATE TABLE QRN_LAST_WORD_LETTER_VERSE(
S INTEGER,
A INTEGER,
A_NUM INTEGER,
ALIF INTEGER,
BA INTEGER,
TA INTEGER,
THA INTEGER,
JIM INTEGER,
HHA INTEGER,
DAL INTEGER,
DHAL INTEGER,
RA INTEGER,
ZAY INTEGER,
SIN INTEGER,
SHIN INTEGER,
SAD INTEGER,
DAD INTEGER,
TAA INTEGER,
ZA INTEGER,
AYN INTEGER,
HAMZA INTEGER,
FA INTEGER,
QAF INTEGER,
KAF INTEGER,
LAM INTEGER,
MIM INTEGER,
NUN INTEGER,
HA INTEGER,
YA INTEGER,
TA_MARBUTA INTEGER,
ALIF_MAQSURA INTEGER,
DERNIERE_LETTRE TEXT,
DERNIER_MOT TEXT
);"

sqlite3 QRN.db <<"EOF"
.mode csv 
.separator "|"
.import quran-uthmani_without_crlf.txt QRN_QURAN_OTHMAN
.import QWLC.txt QRN_QWLC
.import out.txt QRN_LAST_WORD_LETTER_VERSE
.separator ";"
.import Qrn-verse.txt QRN_ABJAD_VERSES
.import Qrn-word.txt QRN_ABJAD_WORDS
.import Surah_description.txt QRN_SURAH_NAME
EOF
